# Partner Distribution Configuration File

[Global]
id=enterprise-stageMozGCP
version=1.0
about=Enterprise stage MozGCP

[Preferences]
enterprise.console.address=https://https://stage.fx-enterprise.nonprod.webservices.mozgcp.net
